server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      test:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
spring:
  application:
    name: book-service
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booksdb?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    flyway:
      url: jdbc:mysql://localhost:3306/
      schemas: booksdb
      user: root
      password: 1234